In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("J:/Data science/data/NLP/npr.csv")

In [3]:
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
count_vec = CountVectorizer(max_df = 0.95 , min_df = 2 , stop_words="english")
matrix_bow = count_vec.fit_transform(df['Article'])

In [6]:
matrix_bow

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [13]:
print(matrix_bow)

  (0, 53112)	2
  (0, 436)	3
  (0, 37382)	2
  (0, 5867)	1
  (0, 37411)	2
  (0, 43740)	1
  (0, 54403)	3
  (0, 44460)	2
  (0, 28875)	3
  (0, 44648)	1
  (0, 16578)	1
  (0, 12950)	1
  (0, 604)	1
  (0, 38079)	6
  (0, 34145)	15
  (0, 32459)	1
  (0, 42732)	1
  (0, 42390)	9
  (0, 2437)	2
  (0, 25508)	5
  (0, 16123)	4
  (0, 26752)	3
  (0, 10646)	1
  (0, 41011)	4
  (0, 29070)	1
  :	:
  (11991, 4315)	1
  (11991, 28887)	1
  (11991, 32585)	1
  (11991, 50599)	1
  (11991, 9067)	1
  (11991, 38652)	1
  (11991, 47768)	2
  (11991, 33536)	1
  (11991, 16527)	1
  (11991, 41081)	1
  (11991, 14611)	1
  (11991, 28356)	1
  (11991, 35785)	1
  (11991, 33620)	14
  (11991, 7316)	1
  (11991, 45088)	1
  (11991, 22720)	1
  (11991, 51838)	1
  (11991, 37235)	1
  (11991, 49654)	1
  (11991, 15275)	1
  (11991, 53567)	1
  (11991, 12752)	1
  (11991, 20202)	1
  (11991, 47633)	11


In [10]:
len(count_vec.get_feature_names())

54777

In [32]:
import random
for i in range(10):
    rand_word_id = random.randint(0,54777)
    print(count_vec.get_feature_names()[rand_word_id])

inconvenience
ariel
newsom
barder
opportunistic
spas
bakery
anytime
specious
principled


In [15]:
from sklearn.decomposition import LatentDirichletAllocation as LDA

In [16]:
lda = LDA(n_components=7)
lda.fit(matrix_bow)

LatentDirichletAllocation(n_components=7)

In [21]:
lda.components_

array([[3.30473381e+01, 9.51600056e+02, 1.42857147e-01, ...,
        1.43219061e-01, 1.14269183e+00, 1.42857144e-01],
       [1.74798417e+01, 2.67750098e+02, 1.42857145e-01, ...,
        2.62498075e+00, 1.14232980e+00, 1.42857143e-01],
       [1.13490361e+00, 1.30457797e+03, 1.42863942e-01, ...,
        1.42912408e-01, 1.42857146e-01, 1.42857143e-01],
       ...,
       [1.69889094e+01, 4.57011926e+02, 1.42857145e-01, ...,
        1.42857145e-01, 1.42857145e-01, 1.42860862e-01],
       [9.10384392e+00, 8.87217110e+02, 1.42857148e-01, ...,
        1.42902075e-01, 1.42857148e-01, 1.42880752e-01],
       [3.10173176e+00, 1.55619348e+03, 1.42857148e-01, ...,
        3.65985408e+00, 1.42990797e-01, 1.42860999e-01]])

In [22]:
lda.components_.shape

(7, 54777)

In [23]:
single_topic = lda.components_[0]
single_topic

array([3.30473381e+01, 9.51600056e+02, 1.42857147e-01, ...,
       1.43219061e-01, 1.14269183e+00, 1.42857144e-01])

In [24]:
single_topic.shape

(54777,)

In [25]:
single_topic.argsort()

array([31115, 33132, 21349, ..., 28659, 33390, 42993], dtype=int64)

In [26]:
single_topic.argsort()[-10:]

array([43238, 49459, 54102, 54412, 36283, 53152, 26752, 28659, 33390,
       42993], dtype=int64)

In [28]:
for i in single_topic.argsort()[-10:]:
    print(count_vec.get_feature_names()[i])

scientists
time
world
years
people
water
just
like
new
says


In [33]:
for i,topic in enumerate(lda.components_):
    print("cluster" , i)
    print([count_vec.get_feature_names()[i] for i in topic.argsort()[-10:]])
    print("\n")

cluster 0
['scientists', 'time', 'world', 'years', 'people', 'water', 'just', 'like', 'new', 'says']


cluster 1
['way', 'don', 'really', 'time', 'know', 'think', 'just', 'like', 'people', 'says']


cluster 2
['women', 'said', 'like', 'students', 'school', 'percent', 'care', 'people', 'health', 'says']


cluster 3
['songs', 'band', 'way', 'time', 'album', 'song', 'just', 'new', 'like', 'music']


cluster 4
['people', 'new', 'obama', 'house', 'campaign', 'state', 'clinton', 'president', 'said', 'trump']


cluster 5
['world', 'state', 'countries', 'country', 'military', 'government', 'war', 'people', 'says', 'said']


cluster 6
['000', 'said', 'money', 'country', 'million', 'year', 'years', 'new', 'people', 'says']




In [34]:
matrix_bow

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [35]:
topic_results = lda.transform(matrix_bow)
topic_results

array([[2.25552143e-04, 2.25470463e-04, 2.25391272e-04, ...,
        7.64945762e-01, 2.33926889e-01, 2.25459619e-04],
       [4.40943070e-04, 2.60133487e-02, 4.40707984e-04, ...,
        5.53187027e-01, 4.19035186e-01, 4.42119280e-04],
       [3.28404737e-04, 3.28603243e-04, 3.28312612e-04, ...,
        8.11604599e-01, 1.86752867e-01, 3.28447035e-04],
       ...,
       [2.49525716e-01, 3.34669399e-01, 1.56007410e-01, ...,
        2.47564839e-02, 1.60275943e-01, 7.43668719e-02],
       [4.32872111e-04, 5.82387482e-02, 4.33298351e-04, ...,
        8.71238779e-01, 2.06354909e-02, 4.85876625e-02],
       [2.54480929e-04, 3.15229398e-01, 2.54380826e-04, ...,
        1.87023001e-01, 2.54507323e-04, 4.96729986e-01]])

In [36]:
topic_results.shape

(11992, 7)

In [38]:
topic_results[0].round(2)

array([0.  , 0.  , 0.  , 0.  , 0.76, 0.23, 0.  ])

In [40]:
topic_results.argmax(axis=1)

array([4, 4, 4, ..., 1, 4, 6], dtype=int64)

In [42]:
df["topic"] = topic_results.argmax(axis=1)
df.head(10)

Article  topic
0  In the Washington of 2016, even when the polic...      4
1    Donald Trump has used Twitter  —   his prefe...      4
2    Donald Trump is unabashedly praising Russian...      4
3  Updated at 2:50 p. m. ET, Russian President Vl...      4
4  From photography, illustration and video, to d...      4
5  I did not want to join yoga class. I hated tho...      2
6  With a   who has publicly supported the debunk...      2
7  I was standing by the airport exit, debating w...      1
8  If movies were trying to be more realistic, pe...      0
9  Eighteen years ago, on New Year’s Eve, David F...      1