In [13]:
import pandas as pd
import numpy as np
import nltk

In [14]:
documents = ["This little kitty came to play when I was eating at a restaurant.",
 "Merley has the best squooshy kitten belly.",
 "Google Translate app is incredible.",
 "If you open 100 tab in google you get a smiley face.",
 "Best cat photo I've ever taken.",
 "Climbing ninja cat.",
 "Impressed with google map feedback.",
 "Key promoter extension for Google Chrome."]

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
tfidf = TfidfVectorizer(stop_words="english")
matrix_tfidf = tfidf.fit_transform(documents)

In [17]:
from sklearn.cluster import KMeans

In [18]:
n_clust = 2
kmean_model = KMeans(n_clusters=n_clust)
kmean_model.fit(matrix_tfidf)

KMeans(n_clusters=2)

In [19]:
kmean_model.cluster_centers_

array([[0.0860499 , 0.10843242, 0.        , 0.        , 0.08164966,
        0.        , 0.09532397, 0.        , 0.08164966, 0.09532397,
        0.0860499 , 0.10843242, 0.2525154 , 0.10843242, 0.10843242,
        0.09532397, 0.        , 0.08164966, 0.08164966, 0.10843242,
        0.        , 0.        , 0.0860499 , 0.        , 0.08164966,
        0.09532397, 0.08164966, 0.0860499 , 0.        , 0.0860499 ,
        0.        , 0.10843242, 0.        ],
       [0.        , 0.        , 0.15371637, 0.26193384, 0.        ,
        0.30304549, 0.        , 0.20277105, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.15371637, 0.        , 0.        , 0.        ,
        0.15371637, 0.20277105, 0.        , 0.15882473, 0.        ,
        0.        , 0.        , 0.        , 0.15371637, 0.        ,
        0.15882473, 0.        , 0.15882473]])

In [20]:
order_centorids = kmean_model.cluster_centers_.argsort()[:,::-1]
order_centorids

array([[12, 31,  1, 11, 13, 19, 14,  9, 25,  6, 15,  0, 29, 27, 10, 22,
         8, 17, 18,  4, 24, 26,  3,  2,  5, 32,  7, 20, 21, 23, 28, 30,
        16],
       [ 5,  3,  7, 21, 32, 23, 30,  2, 20, 16, 28, 22, 10,  1, 29,  4,
        27,  6, 26,  8,  9, 11, 24, 12, 13, 14, 15, 31, 17, 18, 19, 25,
         0]], dtype=int64)

In [21]:
feat = tfidf.get_feature_names()
feat

C:\Users\Abdelrahman\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['100',
 'app',
 'belly',
 'best',
 'came',
 'cat',
 'chrome',
 'climbing',
 'eating',
 'extension',
 'face',
 'feedback',
 'google',
 'impressed',
 'incredible',
 'key',
 'kitten',
 'kitty',
 'little',
 'map',
 'merley',
 'ninja',
 'open',
 'photo',
 'play',
 'promoter',
 'restaurant',
 'smiley',
 'squooshy',
 'tab',
 'taken',
 'translate',
 've']

In [23]:
for i in range(n_clust):
    print("cluster id is " , i)
    for idd in order_centorids[i,:10]:
        print(feat[idd])
    print("--------------")
print("\n")

cluster id is  0
google
translate
app
feedback
impressed
map
incredible
extension
promoter
chrome
--------------
cluster id is  1
cat
best
climbing
ninja
ve
photo
taken
belly
merley
kitten
--------------




In [26]:
y = tfidf.transform(["chrome browser to open"])
y_pred = kmean_model.predict(y)
y_pred

array([0])

In [28]:
y = tfidf.transform(["cat is hungry"])
y_pred = kmean_model.predict(y)
y_pred

array([1])