In [223]:
import pandas as pd
import numpy as np
import tensorflow as tf
import nltk
import string
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [224]:
stop_words_list = nltk.corpus.stopwords.words("english")
lemma_nltk = WordNetLemmatizer()

In [225]:
data = pd.read_csv("J:/Data science/data/NLP/disaster/train.csv")

In [226]:
df = data.sample(frac=1 , random_state=42)
df.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [227]:
df.shape

(7613, 5)

In [228]:
df.target.value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [229]:
def clean_text(text):
    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = word_tokenize(text)
    text = " ".join([lemma_nltk.lemmatize(word) for word in tokens if word not in stop_words_list])
    return text

In [230]:
df['text'] = df['text'].apply(lambda x:clean_text(x))

In [231]:
x = df['text']
y = df['target']

In [232]:
x.head()

2644            new weapon cause unimaginable destruction
2227    famping thing gishwhes got soaked deluge going...
5448    dt georgegalloway rt galloway4mayor ‰ûïthe col...
132     aftershock back school kick great want thank e...
6845    response trauma child addict develop defensive...
Name: text, dtype: object

In [233]:
y.head()

2644    1
2227    0
5448    1
132     0
6845    0
Name: target, dtype: int64

In [234]:
from sklearn.model_selection import train_test_split
x_train ,x_test ,y_train ,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [235]:
sum(set([len(i.split()) for i in x_train]))

325

In [236]:
words = sum([len(i.split()) for i in x_train])
words

53333

In [237]:
words = sum([len(i.split()) for i in x_train])
words

53333

In [238]:
len(x_train)

5329

In [239]:
avg = words / len(x_train)
round(avg)

10

In [240]:
max_tokens = 10000
max_sent_length = 10

In [241]:
# from tensorflow.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.preprocessing.sequence import pad_sequences

In [242]:
# sentences = ["I love my dog",
#              "I love my cat",
#              "You love my dog!",
#              "Do you think my dog is amazing"]

In [243]:
# Deprecated: `tf.keras.preprocessing.text.Tokenizer` does not operate on
# tensors and is not recommended for new code. Prefer
# `tf.keras.layers.TextVectorization` which provides equivalent functionality
# through a layer which accepts `tf.Tensor` input. See the
# [text loading tutorial](https://www.tensorflow.org/tutorials/load_data/text)

# tokenizer = Tokenizer()

In [244]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
text_vectorizer = TextVectorization(max_tokens=max_tokens,
                                   output_sequence_length=max_sent_length)

In [245]:
text_vectorizer.adapt(x_train)

In [246]:
samp_sent = "i love you"
text_vectorizer([samp_sent])

<tf.Tensor: shape=(1, 10), dtype=int64, numpy=array([[ 1, 57,  1,  0,  0,  0,  0,  0,  0,  0]], dtype=int64)>

In [247]:
samp_sent = "i love you and give me your pen to can i write my note"
text_vectorizer([samp_sent])

<tf.Tensor: shape=(1, 10), dtype=int64, numpy=array([[  1,  57,   1,   1, 890,   1,   1,   1,   1,   1]], dtype=int64)>

In [248]:
x_train

2470    modiministry railway minister prabhu call mp d...
3455    man squeeze another man head bare hand literal...
1977    drug alcohol jackson vroman house httptco5oqhq...
7216    danagould waynesteratl agree background check ...
1028    know hate body buy 2 bag chip variety pack fru...
                              ...                        
7090    nytimes due upheaval created west iraq syria l...
629     70 70amp think possibility full transformation...
6464    near sand half sunk shattered visage lie httpt...
6265    kesabaran membuahkan hasil indah pada saat tep...
3723    scottdpierce billharristv harrisgle beezersun ...
Name: text, Length: 5329, dtype: object

In [249]:
from tensorflow.keras import layers
tf.random.set_seed(42)
embdding = layers.Embedding(input_dim=max_tokens,
                            input_length=max_sent_length,
                            output_dim = 64,
                           name="Embedding_1")
embdding

In [250]:
import random
random_sent = random.choice(x_train)
samp_embd = embdding(text_vectorizer([random_sent]))
samp_embd

<tf.Tensor: shape=(1, 10, 64), dtype=float32, numpy=
array([[[ 3.19651030e-02,  1.86757483e-02,  2.60121338e-02,
         -2.36060750e-02,  4.28272970e-02, -3.97839919e-02,
         -2.69624833e-02, -3.67361419e-02,  1.69574656e-02,
         -4.29888815e-03,  9.64790583e-03,  4.82630990e-02,
         -4.39738035e-02, -2.11400520e-02, -4.61020358e-02,
          6.32616132e-03, -1.97188258e-02, -3.58606577e-02,
         -3.83109674e-02, -2.96579003e-02,  3.04114074e-04,
         -3.60473022e-02,  4.99406569e-02,  7.08615780e-03,
          3.23896743e-02, -2.42034327e-02,  1.22763142e-02,
          4.06229533e-02, -1.68006532e-02, -3.77276428e-02,
         -3.54718342e-02, -4.62356471e-02,  1.30284317e-02,
         -7.00091198e-03, -5.19655645e-04,  3.82217281e-02,
          1.08001828e-02, -1.68678910e-03,  2.13031210e-02,
         -2.78166682e-03, -4.29638289e-02,  3.47384252e-02,
         -2.48000752e-02, -1.03521571e-02,  2.81403698e-02,
         -2.51346827e-02,  8.63045454e-03, -4.9

In [251]:
samp_embd[0]
#لكل كلمه embedding خاص بيها 64

<tf.Tensor: shape=(10, 64), dtype=float32, numpy=
array([[ 3.19651030e-02,  1.86757483e-02,  2.60121338e-02,
        -2.36060750e-02,  4.28272970e-02, -3.97839919e-02,
        -2.69624833e-02, -3.67361419e-02,  1.69574656e-02,
        -4.29888815e-03,  9.64790583e-03,  4.82630990e-02,
        -4.39738035e-02, -2.11400520e-02, -4.61020358e-02,
         6.32616132e-03, -1.97188258e-02, -3.58606577e-02,
        -3.83109674e-02, -2.96579003e-02,  3.04114074e-04,
        -3.60473022e-02,  4.99406569e-02,  7.08615780e-03,
         3.23896743e-02, -2.42034327e-02,  1.22763142e-02,
         4.06229533e-02, -1.68006532e-02, -3.77276428e-02,
        -3.54718342e-02, -4.62356471e-02,  1.30284317e-02,
        -7.00091198e-03, -5.19655645e-04,  3.82217281e-02,
         1.08001828e-02, -1.68678910e-03,  2.13031210e-02,
        -2.78166682e-03, -4.29638289e-02,  3.47384252e-02,
        -2.48000752e-02, -1.03521571e-02,  2.81403698e-02,
        -2.51346827e-02,  8.63045454e-03, -4.93625887e-02,
      

In [252]:
samp_embd[0][0]

<tf.Tensor: shape=(64,), dtype=float32, numpy=
array([ 0.0319651 ,  0.01867575,  0.02601213, -0.02360607,  0.0428273 ,
       -0.03978399, -0.02696248, -0.03673614,  0.01695747, -0.00429889,
        0.00964791,  0.0482631 , -0.0439738 , -0.02114005, -0.04610204,
        0.00632616, -0.01971883, -0.03586066, -0.03831097, -0.0296579 ,
        0.00030411, -0.0360473 ,  0.04994066,  0.00708616,  0.03238967,
       -0.02420343,  0.01227631,  0.04062295, -0.01680065, -0.03772764,
       -0.03547183, -0.04623565,  0.01302843, -0.00700091, -0.00051966,
        0.03822173,  0.01080018, -0.00168679,  0.02130312, -0.00278167,
       -0.04296383,  0.03473843, -0.02480008, -0.01035216,  0.02814037,
       -0.02513468,  0.00863045, -0.04936259,  0.0263494 , -0.01202895,
        0.03158307,  0.01311452, -0.00297663,  0.03233702,  0.02519247,
        0.01140825, -0.02719205,  0.04107506,  0.03567905,  0.03362985,
        0.0265684 ,  0.01137234,  0.02290919, -0.00236167], dtype=float32)>

In [253]:
inputs = layers.Input(shape=(1,) , dtype="string")
x = text_vectorizer(inputs)
print(x.shape)
x = embdding(x)
print(x.shape)
x = layers.GlobalAveragePooling1D()(x) #removes 10 (every time step)
print(x.shape)
outputs = layers.Dense(1,activation="sigmoid")(x)
print(outputs.shape)
model_1 = tf.keras.Model(inputs,outputs,name="model_1_dense")

(None, 10)
(None, 10, 64)
(None, 64)
(None, 1)


In [254]:
model_1.compile(loss=tf.keras.losses.binary_crossentropy,
                optimizer = tf.keras.optimizers.Adam(),
                metrics = ["accuracy"])

In [255]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_12 (InputLayer)       [(None, 1)]               0         
                                                                 
 text_vectorization_13 (Text  (None, 10)               0         
 Vectorization)                                                  
                                                                 
 Embedding_1 (Embedding)     (None, 10, 64)            640000    
                                                                 
 global_average_pooling1d_7   (None, 64)               0         
 (GlobalAveragePooling1D)                                        
                                                                 
 dense_22 (Dense)            (None, 1)                 65        
                                                                 
Total params: 640,065
Trainable params: 640,065
Non-t

In [256]:
model_1_history = model_1.fit(x_train,y_train,epochs=10)
model_1_history

Epoch 1/10
167/167 [==============================] - 2s 9ms/step - loss: 0.6414 - accuracy: 0.6823
Epoch 2/10
167/167 [==============================] - 1s 8ms/step - loss: 0.5048 - accuracy: 0.8054
Epoch 3/10
167/167 [==============================] - 1s 8ms/step - loss: 0.3845 - accuracy: 0.8651
Epoch 4/10
167/167 [==============================] - 1s 9ms/step - loss: 0.3071 - accuracy: 0.8934
Epoch 5/10
167/167 [==============================] - 1s 9ms/step - loss: 0.2534 - accuracy: 0.9122
Epoch 6/10
167/167 [==============================] - 1s 9ms/step - loss: 0.2129 - accuracy: 0.9278
Epoch 7/10
167/167 [==============================] - 1s 8ms/step - loss: 0.1803 - accuracy: 0.9452
Epoch 8/10
167/167 [==============================] - 1s 8ms/step - loss: 0.1544 - accuracy: 0.9531
Epoch 9/10
167/167 [==============================] - 2s 10ms/step - loss: 0.1338 - accuracy: 0.9585
Epoch 10/10
167/167 [==============================] - 2s 11ms/step - loss: 0.1171 - accuracy: 0.96

In [257]:
model_1.evaluate(x_test,y_test)

72/72 [==============================] - 0s 2ms/step - loss: 0.5532 - accuracy: 0.7828


[0.5532118678092957, 0.7828371524810791]

In [258]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,TextVectorization, Flatten, LSTM, Dropout, Activation, Embedding, Bidirectional,SimpleRNN

In [259]:
# from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
# text_vector = TextVectorization(max_tokens = max_tokens,
#                                 output_sequence_length=max_sent_length)
# x_train = text_vector.adapt(x_train)

In [260]:
model_2 = Sequential()
model_2.add(tf.keras.Input(shape=(1,) , dtype="string"))
model_2.add(TextVectorization(max_tokens = max_tokens,output_sequence_length=max_sent_length))
model_2.add(Embedding(input_dim = max_tokens , output_dim=64 , input_length=max_sent_length))
# model_2.add(Dropout(0.2))
model_2.add(SimpleRNN(units=64))
# model_2.add(Dropout(0.2))
model_2.add(Dense(1,activation="sigmoid"))

In [261]:
# model_2 = Sequential()
# # model_2.add(Input(shape=(1,) , dtype="string"))
# # model_2.add(TextVectorization(max_tokens = max_tokens,output_sequence_length=max_sent_length))
# model_2.add(Embedding(input_dim = max_tokens , output_dim=64 , input_length=max_sent_length))
# # model_2.add(Dropout(0.2))
# model_2.add(SimpleRNN(units=64))
# # model_2.add(Dropout(0.2))
# model_2.add(Dense(1,activation="sigmoid"))

In [262]:
# model_2 = Sequential()
# model_2.add(embdding)
# model_2.add(Dropout(0.2))
# model_2.add(SimpleRNN(64))
# model_2.add(Dropout(0.2))
# model_2.add(Dense(1,activation="sigmoid"))

In [263]:
model_2.summary()

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 text_vectorization_14 (Text  (None, 10)               0         
 Vectorization)                                                  
                                                                 
 embedding_14 (Embedding)    (None, 10, 64)            640000    
                                                                 
 simple_rnn_15 (SimpleRNN)   (None, 64)                8256      
                                                                 
 dense_23 (Dense)            (None, 1)                 65        
                                                                 
Total params: 648,321
Trainable params: 648,321
Non-trainable params: 0
_________________________________________________________________


In [264]:
model_2.compile(loss=tf.keras.losses.binary_crossentropy,
                optimizer = tf.keras.optimizers.Adam())
                #metrics=["accuracy"])

In [266]:
# model_2_history = model_2.fit(x_train,y_train,epochs=5)
# model_2_history

In [296]:
model = tf.keras.Sequential([
    tf.keras.Input(shape=(1,) , dtype="string"),
    text_vectorizer,
    embdding,
    tf.keras.layers.Dropout(0.2),
#     tf.keras.layers.SimpleRNN(64,return_sequences=True),
#     tf.keras.layers.SimpleRNN(64),
    tf.keras.layers.SimpleRNN(64),
    tf.keras.layers.Dense(64),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1,activation="sigmoid")
])

In [297]:
model.compile(loss=tf.keras.losses.binary_crossentropy,
              optimizer = tf.keras.optimizers.Adam(),
              metrics=["accuracy"])

In [298]:
model.summary()

Model: "sequential_26"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 text_vectorization_13 (Text  (None, 10)               0         
 Vectorization)                                                  
                                                                 
 Embedding_1 (Embedding)     (None, 10, 64)            640000    
                                                                 
 dropout_30 (Dropout)        (None, 10, 64)            0         
                                                                 
 simple_rnn_26 (SimpleRNN)   (None, 64)                8256      
                                                                 
 dense_33 (Dense)            (None, 64)                4160      
                                                                 
 dropout_31 (Dropout)        (None, 64)                0         
                                                     

In [299]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
167/167 [==============================] - 3s 9ms/step - loss: 0.0587 - accuracy: 0.9810
Epoch 2/5
167/167 [==============================] - 1s 9ms/step - loss: 0.0304 - accuracy: 0.9874
Epoch 3/5
167/167 [==============================] - 1s 9ms/step - loss: 0.0273 - accuracy: 0.9886
Epoch 4/5
167/167 [==============================] - 1s 9ms/step - loss: 0.0298 - accuracy: 0.9869
Epoch 5/5
167/167 [==============================] - 2s 10ms/step - loss: 0.0271 - accuracy: 0.9872


In [300]:
model.evaluate(x_test,y_test)

72/72 [==============================] - 0s 2ms/step - loss: 1.2381 - accuracy: 0.7504


[1.2381021976470947, 0.75043785572052]