In [1]:
import pandas as pd
import numpy as np

In [2]:
import tensorflow as tf

In [3]:
import string
import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [4]:
stop_words_list = nltk.corpus.stopwords.words("english")

In [5]:
lemma_nltk = WordNetLemmatizer()

In [6]:
train_df = pd.read_csv("J:/Data science/data/NLP/disaster/train.csv")
test_df = pd.read_csv("J:/Data science/data/NLP/disaster/test.csv")

In [7]:
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [8]:
train_df.shape , test_df.shape

((7613, 5), (3263, 4))

In [9]:
train_df['target'].value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [10]:
train_df_shuffled = train_df.sample(frac=1, random_state=42)
# shuffle with random_state=42 for reproducibility
train_df_shuffled.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [11]:
import random
random_index = random.randint(0 , len(train_df))
for row in train_df_shuffled[['text' , 'target']][random_index:random_index+5].itertuples():
    _ , text , target = row
    print(f"Target: {target}", "(real disaster)" if target > 0 else "(not real disaster)")
    print(f"Text:\n{text}\n")
    print("---\n")

Target: 1 (real disaster)
Text:
Christian Attacked by Muslims at the Temple Mount after Waving Israeli Flag via Pamela Geller - ... http://t.co/yUBKHf9iyh

---

Target: 0 (not real disaster)
Text:
Deal of The Day : http://t.co/US0qQqhQVj Brand New DSERIALPCILP Lava Computer PCI Bus Dual Serial 16550 Board  #e‰Û_ http://t.co/l0b14SJ7JB

---

Target: 1 (real disaster)
Text:
I came up with an idea of a fragrance concept for a bath bomb called The Blood of my Enemies. So you can say that's what you bathe in.

---

Target: 0 (not real disaster)
Text:
@Collapsed thank u

---

Target: 0 (not real disaster)
Text:
Woke up to Drake body bagging Meek again!! Meek u can't out spit ya girlfriend... Just lay down Man.... NOT Right... http://t.co/6CraEKc9wb

---



In [12]:
train_df_shuffled['text'][:3]

2644    So you have a new weapon that can cause un-ima...
2227    The f$&amp;@ing things I do for #GISHWHES Just...
5448    DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...
Name: text, dtype: object

In [13]:
def clean_text(text):
    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = word_tokenize(text)
    text = " ".join([lemma_nltk.lemmatize(word) for word in tokens if word not in stop_words_list])
    return text

In [14]:
train_df_shuffled['text'] = train_df_shuffled['text'].apply(lambda x:clean_text(x))

In [15]:
train_df_shuffled.text

2644            new weapon cause unimaginable destruction
2227    famping thing gishwhes got soaked deluge going...
5448    dt georgegalloway rt galloway4mayor ‰ûïthe col...
132     aftershock back school kick great want thank e...
6845    response trauma child addict develop defensive...
                              ...                        
5226    eganator2000 arent many obliteration server al...
5390    panic attack bc dont enough money drug alcohol...
860     omron hem712c automatic blood pressure monitor...
7603    official say quarantine place alabama home pos...
7270    moved england five year ago today whirlwind ti...
Name: text, Length: 7613, dtype: object

In [16]:
train_df_shuffled.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644          new weapon cause unimaginable destruction       1  
2227  famping thing gishwhes got soaked deluge going...       0  
5448  dt georgegalloway rt galloway4mayor ‰ûïthe col...       1  
132   aftershock back school kick great want thank e...       0  
6845  response trauma child addict develop defensive...       0

In [17]:
x = train_df_shuffled['text']
y = train_df_shuffled['target']

In [18]:
x.head(2)

2644            new weapon cause unimaginable destruction
2227    famping thing gishwhes got soaked deluge going...
Name: text, dtype: object

In [19]:
y.head(2)

2644    1
2227    0
Name: target, dtype: int64

In [120]:
from sklearn.model_selection import train_test_split
x_train ,x_test , y_train , y_test = train_test_split(x,y,test_size=0.30,random_state=42)

In [118]:
x_train.head()

2710    detonation fashionable mountaineering electron...
3250    men escape car engulfed flame parley canyon cr...
78      i77 mile marker 31 40 south mooresville iredel...
1621    greece tax revenue collapse debt crisis contin...
2528    afraid sudden fear neither desolation wicked c...
Name: text, dtype: object

In [22]:
x_test.head()

4955    dfr ep016 monthly meltdown dnbheaven 20150806 ...
584     fedex longer transport bioterror germ wake ant...
7411    gunman kill four el salvador bus attack suspec...
5950      camilacabello97 internally externally screaming
5541    radiation emergency preparedness start knowing...
Name: text, dtype: object

In [121]:
y_train.head()

2470    1
3455    0
1977    0
7216    0
1028    0
Name: target, dtype: int64

In [122]:
y_test.head()

4955    0
584     0
7411    1
5950    1
5541    1
Name: target, dtype: int64

In [25]:
y_train.shape , y_test.shape

((6090,), (1523,))

In [26]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

In [27]:
vectorizer = TextVectorization(max_tokens=None,
                               standardize="lower_and_strip_punctuation",
                               split="whitespace",
                               ngrams=None,
                               output_mode="int",
                               output_sequence_length=None)
                              # appad_to_max_tokens=True)

In [31]:
x_train.head()

2710    detonation fashionable mountaineering electron...
3250    men escape car engulfed flame parley canyon cr...
78      i77 mile marker 31 40 south mooresville iredel...
1621    greece tax revenue collapse debt crisis contin...
2528    afraid sudden fear neither desolation wicked c...
Name: text, dtype: object

In [54]:
words = sum([len(i.split()) for i in x_train])
words

61134

In [55]:
x_train_len = len(x_train)
x_train_len

6090

In [58]:
avg = words / x_train_len
round(avg)

10

In [57]:
# output_sequence_length = 10

In [59]:
max_tokens = 10000
max_sent_length = 10 

text_vectorizer = TextVectorization(max_tokens=max_tokens,
                                    output_sequence_length=max_sent_length,
                                   output_mode="int")

In [81]:
text_vectorizer.adapt(x_train)

In [66]:
sample_sentence = "There's a flood in my street!"
print(text_vectorizer([sample_sentence]))
print("shape",text_vectorizer([sample_sentence]).shape)

tf.Tensor([[  1   1  50   1   1 449   0   0   0   0]], shape=(1, 10), dtype=int64)
shape (1, 10)


In [67]:
sample_sentence = "There's a flood in my street you are very good student and i have mony"
print(text_vectorizer([sample_sentence]))
print("shape",text_vectorizer([sample_sentence]).shape)

tf.Tensor([[  1   1  50   1   1 449   1   1   1  79]], shape=(1, 10), dtype=int64)
shape (1, 10)


In [87]:
random_sentence = random.choice(x_train)
print(f"Original text:\n{random_sentence}\
      \n\nVectorized version:")
text_vectorizer([random_sentence])

Original text:
guess ill never able go mayhem      

Vectorized version:


<tf.Tensor: shape=(1, 10), dtype=int64, numpy=
array([[1090,  334,  133, 1322,   30,  684,    0,    0,    0,    0]],
      dtype=int64)>

In [88]:
text_vectorizer.get_vocabulary()

['',
 '[UNK]',
 'like',
 'fire',
 'im',
 'amp',
 'u',
 'get',
 'via',
 'new',
 'people',
 'news',
 'one',
 'dont',
 'video',
 '2',
 'time',
 'emergency',
 'disaster',
 'body',
 'year',
 'day',
 'family',
 'storm',
 'home',
 'still',
 'building',
 'say',
 'life',
 'would',
 'go',
 'police',
 'crash',
 'world',
 'back',
 'train',
 'suicide',
 'california',
 'bomb',
 'man',
 'see',
 'car',
 'burning',
 'look',
 'know',
 'rt',
 'got',
 'first',
 'death',
 'going',
 'flood',
 'attack',
 'make',
 'nuclear',
 'want',
 'love',
 'war',
 'cant',
 'accident',
 'youtube',
 'let',
 'today',
 'killed',
 'woman',
 'two',
 'weapon',
 'could',
 'take',
 'many',
 '3',
 'watch',
 'dead',
 'need',
 'way',
 'injury',
 'full',
 'think',
 'may',
 'hiroshima',
 'good',
 'wildfire',
 'last',
 'service',
 'bag',
 'collapse',
 'na',
 'help',
 'come',
 'best',
 'work',
 'mass',
 'plan',
 'kill',
 'god',
 'even',
 'city',
 'bombing',
 'black',
 'lol',
 'fatality',
 'really',
 'please',
 'mh370',
 'fatal',
 'legion

In [89]:
len(text_vectorizer.get_vocabulary())

10000

In [91]:
words = text_vectorizer.get_vocabulary()
top_words = words[:10]
print("top_words" , top_words)
lowest_words = words[-10:]
print("lowest words" , lowest_words)

top_words ['', '[UNK]', 'like', 'fire', 'im', 'amp', 'u', 'get', 'via', 'new']
lowest words ['judicial', 'judgement', 'judemugabi', 'juda', 'juanny', 'juanmthompson', 'juan', 'jtw', 'jtruff23', 'jsunnews']


In [92]:
from tensorflow.keras import layers

In [93]:
tf.random.set_seed(42)
embedding = layers.Embedding(input_dim = max_tokens,
                             input_length=max_sent_length,
                             output_dim=128,
                             embeddings_initializer = "uniform",
                             name = "embedding_1"
                            )
embedding

In [96]:
rand_sent = random.choice(x_train)
print("random sent is " , rand_sent)
sample_embedding = embedding(text_vectorizer([random_sent]))
sample_embedding

random sent is  drowned kiddie pool lost ploppy


<tf.Tensor: shape=(1, 10, 128), dtype=float32, numpy=
array([[[-0.03048784,  0.04003957,  0.01426423, ...,  0.04380543,
         -0.01184901,  0.04811785],
        [-0.01329229, -0.0147266 ,  0.00419713, ..., -0.03373086,
         -0.01940848, -0.02834207],
        [ 0.00668001, -0.04291473,  0.00131118, ...,  0.04559691,
          0.0180651 , -0.0089489 ],
        ...,
        [ 0.03977952, -0.03782602, -0.03646283, ...,  0.00236253,
          0.03332629,  0.02803668],
        [ 0.03977952, -0.03782602, -0.03646283, ...,  0.00236253,
          0.03332629,  0.02803668],
        [ 0.01645621, -0.00589932, -0.01471175, ..., -0.02511839,
          0.00912381, -0.00024097]]], dtype=float32)>

In [103]:
# sample_embedding for single token
sample_embedding[0][0]

<tf.Tensor: shape=(128,), dtype=float32, numpy=
array([-0.03048784,  0.04003957,  0.01426423, -0.009557  ,  0.02617123,
       -0.0296874 , -0.00520356, -0.0015491 , -0.0432423 ,  0.03947959,
       -0.01599623, -0.00307544,  0.03297296,  0.00674161,  0.00999154,
       -0.01785795, -0.01865766, -0.00477596,  0.00252626, -0.03301965,
       -0.02574833, -0.02735887,  0.04895354, -0.02428398, -0.03284209,
       -0.01870733,  0.00711773,  0.01872716, -0.00550957, -0.03287035,
        0.00234555,  0.04410351, -0.03565437, -0.01922593,  0.02827149,
        0.0436686 ,  0.00345143, -0.0235054 , -0.04512234,  0.04664881,
        0.00074053, -0.03666414, -0.00098949, -0.00345348,  0.01539921,
        0.02117733, -0.04298643,  0.04409125, -0.03413866, -0.03797597,
       -0.02278177, -0.03870352,  0.0427174 ,  0.01543829,  0.0360924 ,
       -0.03057199, -0.03195395, -0.02997066, -0.01305727,  0.02030683,
       -0.00475283,  0.03603263, -0.01161944,  0.04248586,  0.02816181,
       -0.030615

In [105]:
# sample_embedding for single doc(tweet)
sample_embedding[0]

<tf.Tensor: shape=(10, 128), dtype=float32, numpy=
array([[-0.03048784,  0.04003957,  0.01426423, ...,  0.04380543,
        -0.01184901,  0.04811785],
       [-0.01329229, -0.0147266 ,  0.00419713, ..., -0.03373086,
        -0.01940848, -0.02834207],
       [ 0.00668001, -0.04291473,  0.00131118, ...,  0.04559691,
         0.0180651 , -0.0089489 ],
       ...,
       [ 0.03977952, -0.03782602, -0.03646283, ...,  0.00236253,
         0.03332629,  0.02803668],
       [ 0.03977952, -0.03782602, -0.03646283, ...,  0.00236253,
         0.03332629,  0.02803668],
       [ 0.01645621, -0.00589932, -0.01471175, ..., -0.02511839,
         0.00912381, -0.00024097]], dtype=float32)>

In [106]:
x_train.head()

2710    detonation fashionable mountaineering electron...
3250    men escape car engulfed flame parley canyon cr...
78      i77 mile marker 31 40 south mooresville iredel...
1621    greece tax revenue collapse debt crisis contin...
2528    afraid sudden fear neither desolation wicked c...
Name: text, dtype: object

In [107]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix , accuracy_score

In [123]:
model_0 = Pipeline([
                    ("tfidf", TfidfVectorizer()), # convert words to numbers using tfidf
                    ("clf", MultinomialNB()) # model the text
])
model_0.fit(x_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [124]:
y_pred = model_0.predict(x_test)
y_pred

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

In [125]:
y_pred.shape

(2284,)

In [126]:
conf = confusion_matrix(y_test , y_pred)
conf

array([[1164,   97],
       [ 379,  644]], dtype=int64)

In [127]:
accuracy_score(y_test , y_pred)*100

79.15936952714536